<h1><center>MAST30034 Applied Data Science</center></h1><body><center>Dataset Choosing for Group Project</center></body>

In [24]:
import pandas as pd
import numpy as np
import geopandas as gpd
import folium
import seaborn as sns
from numpy import log, sqrt
import matplotlib.pyplot as plt
from statsmodels.formula.api import ols
from shapely.geometry import Point, Polygon
import pyspark
import math
from time import time as time

## Sentiment140 dataset with 1.6 million tweets (https://www.kaggle.com/kazanova/sentiment140)
### Sentiment analysis with tweets

In [16]:
df = pd.read_csv("data/Sentiment_analysis_with_tweets.csv", header=None, encoding='latin-1')
df.rename(columns={0: "target", 1: "id", 2: "date", 3: "flag", 4: "user", 5: "text"}, inplace=True)
df.head(10)

,target,id,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
5,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew
6,0,1467811592,Mon Apr 06 22:20:03 PDT 2009,NO_QUERY,mybirch,Need a hug
7,0,1467811594,Mon Apr 06 22:20:03 PDT 2009,NO_QUERY,coZZ,@LOLTrish hey long time no see! Yes.. Rains a...
8,0,1467811795,Mon Apr 06 22:20:05 PDT 2009,NO_QUERY,2Hood4Hollywood,@Tatiana_K nope they didn't have it
9,0,1467812025,Mon Apr 06 22:20:09 PDT 2009,NO_QUERY,mimismo,@twittera que me muera ?

In [18]:
df["date"].describe()

count                          1600000
unique                          774363
top       Mon Jun 15 12:53:14 PDT 2009
freq                                20
Name: date, dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600000 entries, 0 to 1599999
Data columns (total 6 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   0       1600000 non-null  int64
 1   1       1600000 non-null  int64
 2   2       1600000 non-null  object
 3   3       1600000 non-null  object
 4   4       1600000 non-null  object
 5   5       1600000 non-null  object
dtypes: int64(2), object(4)
memory usage: 73.2+ MB

## Trending YouTube Video Statistics (https://www.kaggle.com/datasnaek/youtube-new)
### Daily statistics for trending YouTube videos

In [19]:
df = pd.read_csv("data/TrendingYouTubeVideoStatistics/CAvideos.csv")
df.head(10)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...
5,0yIWz1XEeyc,17.14.11,Jake Paul Says Alissa Violet CHEATED with LOGA...,DramaAlert,25,2017-11-13T07:37:51.000Z,"#DramaAlert|""Drama""|""Alert""|""DramaAlert""|""keem...",1309699,103755,4613,12143,https://i.ytimg.com/vi/0yIWz1XEeyc/default.jpg,False,False,False,► Follow for News! - https://twitter.com/KEEMS...
6,_uM5kFfkhB8,17.14.11,Vanoss Superhero School - New Students,VanossGaming,23,2017-11-12T23:52:13.000Z,"Funny Moments|""Montage video games""|""gaming""|""...",2987945,187464,9850,26629,https://i.ytimg.com/vi/_uM5kFfkhB8/default.jpg,False,False,False,Vanoss Merch Shop: https://vanoss.3blackdot.co...
7,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57534,2967,15959,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
8,JzCsM1vtn78,17.14.11,THE LOGANG MADE HISTORY. LOL. AGAIN.,Logan Paul Vlogs,24,2017-11-12T20:19:24.000Z,"logan paul vlog|""logan paul""|""logan""|""paul""|""o...",4477587,292837,4123,36391,https://i.ytimg.com/vi/JzCsM1vtn78/default.jpg,False,False,False,Join the movement. Be a Maverick ► https://Sho...
9,43sm-QwLcx4,17.14.11,Finally Sheldon is winning an argument about t...,Sheikh Musa,22,2017-11-10T14:10:46.000Z,"God|""Sheldon Cooper""|""Young Sheldon""",505161,4135,976,1484,https://i.ytimg.com/vi/43sm-QwLcx4/default.jpg,False,False,False,Sheldon is roasting pastor of the church\nyoun...

In [20]:
df = pd.read_json("data/TrendingYouTubeVideoStatistics/CA_category_id.json")
df.head(10)

,kind,etag,items
0,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
1,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
2,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
3,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
4,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
5,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
6,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
7,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
8,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
9,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."

## Human Activity Recognition from Continuous Ambient Sensor Data Data Set
### (https://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+from+Continuous+Ambient+Sensor+Data)

In [21]:
df = pd.read_csv("data/casas/csh101/csh101.ann.features.csv")
df.head()

,lastSensorEventHours,lastSensorEventSeconds,lastSensorDayOfWeek,windowDuration,timeSinceLastSensorEvent,prevDominantSensor1,prevDominantSensor2,lastSensorID,lastSensorLocation,lastMotionLocation,...,sensorElTime-Chair,sensorElTime-DiningRoom,sensorElTime-Hall,sensorElTime-Ignore,sensorElTime-Kitchen,sensorElTime-LivingRoom,sensorElTime-Office,sensorElTime-OutsideDoor,sensorElTime-WorkArea,activity
0,10.0,38464.0,4.0,130.0,0.0,0.0,0.0,5.0,5.0,9.0,...,86400.0,86400.0,86400.0,0.000000,86400.0,86400.0,86400.0,1.816728,86400.0,Step_Out
1,10.0,38465.0,4.0,131.0,1.0,0.0,0.0,9.0,9.0,9.0,...,86400.0,86400.0,86400.0,0.055818,86400.0,86400.0,86400.0,0.000000,86400.0,Step_Out
2,10.0,38578.0,4.0,241.0,113.0,0.0,0.0,5.0,5.0,9.0,...,86400.0,86400.0,86400.0,0.000000,86400.0,86400.0,86400.0,113.423815,86400.0,Step_Out
3,10.0,38582.0,4.0,244.0,4.0,0.0,0.0,5.0,5.0,9.0,...,86400.0,86400.0,86400.0,0.000000,86400.0,86400.0,86400.0,117.696845,86400.0,Step_Out
4,10.0,38582.0,4.0,243.0,0.0,0.0,0.0,9.0,9.0,9.0,...,86400.0,86400.0,86400.0,0.063296,86400.0,86400.0,86400.0,0.000000,86400.0,Step_Out

In [4]:
df.describe()

,lastSensorEventHours,lastSensorEventSeconds,lastSensorDayOfWeek,windowDuration,timeSinceLastSensorEvent,prevDominantSensor1,prevDominantSensor2,lastSensorID,lastSensorLocation,lastMotionLocation,...,sensorElTime-Bedroom,sensorElTime-Chair,sensorElTime-DiningRoom,sensorElTime-Hall,sensorElTime-Ignore,sensorElTime-Kitchen,sensorElTime-LivingRoom,sensorElTime-Office,sensorElTime-OutsideDoor,sensorElTime-WorkArea
count,321428.000000,321428.000000,321428.000000,321428.000000,321428.000000,321428.000000,321428.000000,321428.000000,321428.000000,321428.000000,...,321428.000000,321428.0,321428.000000,321428.0,321428.000000,321428.000000,321428.000000,321428.0,321428.000000,321428.0
mean,12.529724,46924.419995,3.098949,464.204251,16.007103,4.311939,4.311846,4.535482,4.535482,4.341016,...,3294.906170,86400.0,5999.858549,86400.0,128.324767,4376.334416,1349.653445,86400.0,3908.285424,86400.0
std,5.751412,20770.004798,2.025850,1177.608470,111.117938,2.789936,2.790064,2.578490,2.578490,3.179820,...,5276.865997,0.0,7951.364867,0.0,877.209809,6329.825193,4630.697184,0.0,5530.714899,0.0
min,0.000000,0.000000,0.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,...,0.000000,86400.0,0.000000,86400.0,0.000000,0.000000,0.000000,86400.0,0.000000,86400.0
25%,9.000000,33548.000000,1.000000,49.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,47.677834,86400.0,503.956040,86400.0,0.000000,142.045953,0.000000,86400.0,297.368259,86400.0
50%,12.000000,43553.000000,3.000000,111.000000,1.000000,5.000000,5.000000,5.000000,5.000000,6.000000,...,993.968133,86400.0,3071.203414,86400.0,1.124736,1898.917008,102.058316,86400.0,1623.830163,86400.0
75%,17.000000,62899.000000,5.000000,442.000000,4.000000,7.000000,7.000000,7.000000,7.000000,7.000000,...,4868.671224,86400.0,8105.401344,86400.0,18.756296,5821.637347,595.838595,86400.0,5371.975932,86400.0
max,23.000000,86399.000000,6.000000,23266.000000,12183.000000,9.000000,9.000000,9.000000,9.000000,9.000000,...,86400.000000,86400.0,86400.000000,86400.0,18258.224368,86400.000000,86400.000000,86400.0,41625.993323,86400.0

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 321428 entries, 0 to 321427
Data columns (total 37 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   lastSensorEventHours      321428 non-null  float64
 1   lastSensorEventSeconds    321428 non-null  float64
 2   lastSensorDayOfWeek       321428 non-null  float64
 3   windowDuration            321428 non-null  float64
 4   timeSinceLastSensorEvent  321428 non-null  float64
 5   prevDominantSensor1       321428 non-null  float64
 6   prevDominantSensor2       321428 non-null  float64
 7   lastSensorID              321428 non-null  float64
 8   lastSensorLocation        321428 non-null  float64
 9   lastMotionLocation        321428 non-null  float64
 10  complexity                321428 non-null  float64
 11  activityChange            321428 non-null  float64
 12  areaTransitions           321428 non-null  float64
 13  numDistinctSensors        321428 non-null  float64
 14  sensorCount-Bathroom      321428 non-null  float64
 15  sensorCount-Bedroom       321428 non-null  float64
 16  sensorCount-Chair         321428 non-null  float64
 17  sensorCount-DiningRoom    321428 non-null  float64
 18  sensorCount-Hall          321428 non-null  float64
 19  sensorCount-Ignore        321428 non-null  float64
 20  sensorCount-Kitchen       321428 non-null  float64
 21  sensorCount-LivingRoom    321428 non-null  float64
 22  sensorCount-Office        321428 non-null  float64
 23  sensorCount-OutsideDoor   321428 non-null  float64
 24  sensorCount-WorkArea      321428 non-null  float64
 25  sensorElTime-Bathroom     321428 non-null  float64
 26  sensorElTime-Bedroom      321428 non-null  float64
 27  sensorElTime-Chair        321428 non-null  float64
 28  sensorElTime-DiningRoom   321428 non-null  float64
 29  sensorElTime-Hall         321428 non-null  float64
 30  sensorElTime-Ignore       321428 non-null  float64
 31  sensorElTime-Kitchen      321428 non-null  float64
 32  sensorElTime-LivingRoom   321428 non-null  float64
 33  sensorElTime-Office       321428 non-null  float64
 34  sensorElTime-OutsideDoor  321428 non-null  float64
 35  sensorElTime-WorkArea     321428 non-null  float64
 36  activity                  321428 non-null  object
dtypes: float64(36), object(1)
memory usage: 90.7+ MB

In [23]:
df1 = pd.read_csv("data/casas/csh101/csh101.rawdata.features.csv")
df1.head()

,lastSensorEventHours,lastSensorEventSeconds,lastSensorDayOfWeek,windowDuration,timeSinceLastSensorEvent,prevDominantSensor1,prevDominantSensor2,lastSensorID,lastSensorLocation,lastMotionLocation,...,sensorElTime-Chair,sensorElTime-DiningRoom,sensorElTime-Hall,sensorElTime-Ignore,sensorElTime-Kitchen,sensorElTime-LivingRoom,sensorElTime-Office,sensorElTime-OutsideDoor,sensorElTime-WorkArea,activity
0,12.0,46486.0,2.0,1.0,0.0,0.0,0.0,5.0,5.0,9.0,...,86400.0,86400.0,86400.0,0.0,0.424354,0.330546,86400.0,0.023716,86400.0,?
1,12.0,46486.0,2.0,1.0,0.0,0.0,0.0,5.0,5.0,9.0,...,86400.0,86400.0,86400.0,0.0,0.445556,0.351748,86400.0,0.044918,86400.0,?
2,12.0,46486.0,2.0,1.0,0.0,0.0,0.0,5.0,5.0,9.0,...,86400.0,86400.0,86400.0,0.0,0.490056,0.396248,86400.0,0.089418,86400.0,?
3,12.0,46486.0,2.0,1.0,0.0,0.0,0.0,5.0,5.0,9.0,...,86400.0,86400.0,86400.0,0.0,0.511291,0.417483,86400.0,0.110653,86400.0,?
4,12.0,46486.0,2.0,1.0,0.0,0.0,0.0,5.0,5.0,9.0,...,86400.0,86400.0,86400.0,0.0,0.532032,0.438224,86400.0,0.131394,86400.0,?

## Appendix

In [3]:
df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20, df21, df22, df23 ,df24])